name: Stack

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  test:
    strategy:
      matrix:
        runner:
          - ubuntu-latest

        resolver:
          - nightly
          - lts       # ghc-9.6 (as of writing)
          - lts-21.25 # ghc 9.4
          - lts-20.26 # ghc-9.2
          - lts-19.33 # ghc-9.0
          - lts-18.9  # ghc-8.10

      fail-fast: false

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v3

      # - name: Install system dependencies
      #   run: |
      #     sudo apt-get install --yes glpk-utils libglpk-dev

      - uses: freckle/stack-action@v3

      - id: stack
        uses: freckle/stack-action@v3
        with:
          stack-arguments: --resolver ${{ matrix.resolver }} --copy-bins --coverage

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ${{ steps.stack.outputs.local-hpc-root }}